Supermarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),
    url(r'^', include('goods.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^order/', include('order.urls')),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add(\d+)_(\d+)/$', views.add, name='add'),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name='edit'),
    url(r'^delete(\d+)/$', views.delete, name='delete'),
]

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^info/$', views.info, name='info'),
    url(r'^register_exist/$', views.register_exist, name='register_exist'),
    url(r'^site/$', views.site, name='site'),
    url(r'^user_center_order&(\d+)/$', views.user_center_order),
    url(r'^logout/$', views.logout, name='logout'),
]

order/models.py
from django.db import models

# Create your models here.


class Order(models.Model):
    """订单"""
    order_id = models.CharField(max_length=20, primary_key=True)
    order_user = models.ForeignKey('user.User')
    order_date = models.DateTimeField(auto_now=True)
    order_IsPay = models.IntegerField(default=0)
    order_total = models.DecimalField(max_digits=6, decimal_places=2)
    order_address = models.CharField(max_length=150, default='')
    order_Pay = models.IntegerField(default=0)


class OrderDetail(models.Model):
    order_goods = models.ForeignKey('goods.Goods')
    order = models.ForeignKey(Order)
    order_price = models.DecimalField(max_digits=5, decimal_places=2)
    order_count = models.IntegerField()

user/models.py
from django.db import models
# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=40)
    email = models.EmailField(max_length=100)
    addressee = models.CharField(max_length=60, default='')
    address = models.TextField(default='')
    post_code = models.CharField(max_length=40, default='')
    phone = models.CharField(max_length=20, default='')
    time = models.DateTimeField(auto_now_add=True)
    # default, blank是python层面的约束,不影响数据库表结构, 不需要迁移

user/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from order.models import Order
from user.models import User
# from hashlib import sha1
# Create your views here.


def register(request):
    """注册"""
    if request.method == 'POST':
        # 接收用户信息
        post = request.POST
        name = post.get('user_name')
        password = post.get('pwd')
        password2 = post.get('cpwd')
        email = post.get('email')
        # 判断两次密码
        if password != password2:
            return redirect('/user/register')
        # 密码加密
        # s1 = sha1()
        # s1.update(password.encode("utf-8"))
        # password3 = s1.hexdigest()
        """创建user/models的对象"""
        user = User()
        user.name = name
        user.password = password
        user.email = email
        user.save()
        """注册成功,转到登录页面"""
        return redirect('/user/login')
    return render(request, 'user/register.html')


def register_exist(requset):
    """判断用户是否已经存在"""
    name = requset.GET.get('uname')
    count = User.objects.filter(name=name).count()
    return JsonResponse({'count': count})


def login(request):
    """登录"""
    uname = request.COOKIES.get('uname', '')
    """登录校验"""
    if request.method == 'POST':
        # 接收请求信息
        post = request.POST
        username = post.get('username')
        password = post.get('pwd')
        remember = post.get('jizhu', 0)
        """根据用户名查询对象"""
        user = User.objects.filter(name=username)
        # print(username)
        # 判断如果未查到则用户名错，查到再判断密码是否正确，正确则转到用户中心
        if len(user) == 1:
            # 密码加密
            # s1 = sha1()
            # s1.update(password.encode("utf-8"))
            # password2 = s1.hexdigest()
            # 登录带cookie值   必须 red = HttpResponseRedirect    red.set_cookie  renturn red
            if password == user[0].password:
                red = HttpResponseRedirect('/')
                # print '*'*10
                # print count
                # 记住用户名
                if remember != 0:
                    red.set_cookie('uname', username)
                else:
                    red.set_cookie('uname', '', max_age=-1)

                request.session['user_id'] = user[0].id
                request.session['user_name'] = username
                return red
            else:
                context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': username}
                return render(request, 'user/login.html', context)
        else:
            context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': username}
            return render(request, 'user/login.html', context)

    context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'user/login.html', context)


def info(request):
    # 从模型中获取用户的email
    email = User.objects.get(id=request.session['user_id']).email

    context = {'title': '天天生鲜用户中心', 'user_email': email, 'user_name': request.session['user_name']}
    return render(request, 'user/user_center_info.html', context)


def site(request):
    """从模型中获取当前用户信息"""
    user = User.objects.get(id=request.session['user_id'])
    user_address = user.address
    user_addressee = user.addressee
    user_phone = user.phone
    user_post_code = user.post_code
    if request.method == 'POST':
        """接收表单信息"""
        user.address = request.POST.get('uaddress')
        user.addressee = request.POST.get('ushou')
        user.post_code = request.POST.get('uyoubian')
        user.phone = request.POST.get('uphone')
        user.save()

        return HttpResponseRedirect('/user/site/')

    context = {'user_address': user_address, 'user_addressee': user_addressee,
               'user_phone': user_phone, 'user_post_code': user_post_code}
    return render(request, 'user/user_center_site.html', context)


def user_center_order(request, page_id):
    """
    此页面用于展示用户提交的订单,由购物车页面下单后调转过来
    也可以从个人信息页面查看,根据用户订单是否支付,下单顺序进行排序
    """
    user_id = request.session.get('user_id')
    # 订单信息 根据是否支付,下单顺序进行排序
    order = Order.objects.filter(order_user_id=user_id).order_by('order_Pay', '-order_id')
    """分页, 获取order list 以两个为一页的list"""
    paginator = Paginator(order, 2)
    # 获取上面集合的第page_id个值
    order_list = paginator.page(int(page_id))
    # 获取一共多少页
    page_list = paginator.page_range
    """上一页(Previous page) 当前页(current page) 下一页(Next page)"""
    page_previous = 0
    page_next = 0
    page_current = int(page_id)
    len_page_list = len(page_list)
    if page_current > 1:
        page_previous = page_current - 1
    if page_current < len_page_list:
        page_next = page_current + 1

    # 构造上下文
    context = {'page_name': 1, 'title': '全部订单', 'page_id': page_current,
               'order': 1, 'order_list': order_list, 'page_list': page_list, 'page_previous': page_previous,
               'page_next': page_next, 'len_page_list': len_page_list}

    return render(request, 'user/user_center_order.html', context)


def logout(request):
    """清除session"""
    request.session.flush()

    return HttpResponseRedirect(reverse('index'))

templates/user/base.html
{% extends 'base.html' %}
{% block body %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="/user/info" {% if info %} class="active" {% endif %}>· 个人信息</a></li>
            <li><a href="/user/user_center_order&1/" {% if order %} class="active" {% endif %}>· 全部订单</a></li>
            <li><a href="/user/site" {% if site %} class="active" {% endif %}>· 收货地址</a></li>
        </ul>
    </div>
    {% block right_content %}
    {% endblock right_content %}
</div>
{% endblock body %}

templates/user/login.html
{% extends 'base_foot.html' %}
{% block head %}
<script>
	$(function () {
        name_error=false
        pwd_error=false
        if($('.name_input').val().length!=0){
            name_error = true
        }
        if($('.pwd_error').val().length!=0){
            pwd_error = true
        }



        if({{ error_name }}== 1){
            $('.user_error').html('用户名错误').show();
        }
        if({{ error_pwd }}== 1){
            $('.pwd_error').html('密码错误').show()
        }
        $('.name_input').blur(function () {
            if($('.name_input').val().length==0){
                $('.user_error').html('请填写用户名').show();
                name_error=false;
            }else {
                $('.user_error').hide()
                name_error=true;
            }

        })
        $('.pass_input').blur(function () {
            if($('.pass_input').val().length==0){
                $('.pwd_error').html('请写密码').show();
                pwd_error=false
            }
            else {$('.pwd_error').hide()
                pwd_error=true}
        })

        $(":submit[id=lo]").click(function(check){
            console.log(pwd_error,name_error)
        if(pwd_error==false || name_error==false){
           check.preventDefault();//此处阻止提交表单
        }
    });

    })

</script>
{% endblock head %}
{% block body %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo">
            <img src="/static/images/logo02.png">
        </a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="/user/register/">立即注册</a>
                </div>
                <div class="form_input">
                    <form id="form" action="/user/login/" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="jizhu" value="1">
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input id="lo" type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/user/register.html
{% extends 'base_foot.html' %}
{% load static from staticfiles %}
{% block head %}
<script type="text/javascript" src="{% static  'js/register.js' %}"></script>

{% endblock head %}


{% block body %}
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="/static/images/logo02.png"></a>
        <div class="reg_slogan">足不出户 · 新鲜每一天</div>
        <div class="reg_banner"></div>
    </div>

    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>用户注册</h1>
            <a href="/user/login/">登录</a>
        </div>
        <div class="reg_form clearfix">
            <form action="/user/register/" id="reg_form" method="post">
                {% csrf_token %}
                <ul>
                    <li>
                        <label>用户名:</label>
                        <input type="text" name="user_name" id="user_name">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>密码:</label>
                        <input type="password" name="pwd" id="pwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>确认密码:</label>
                        <input type="password" name="cpwd" id="cpwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>邮箱:</label>
                        <input type="text" name="email" id="email">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>同意”天天生鲜用户使用协议“</label>
                        <span class="error_tip2">提示信息</span>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="注 册" name="">
                        {#
                        <button type="submit" value="注 册"></button>
                        #}
                    </li>
                </ul>
            </form>
        </div>

    </div>

</div>
{% endblock body %}

templates/user/user_center_info.html
{%extends 'user/base.html'%}
{% block right_content %}
<div class="right_content clearfix">
    <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
        <ul class="user_info_list">
            <li><span>用户名：</span>{{user_name}}</li>
            <li><span>联系方式：</span>{{user_email}}</li>
            <li><span>联系地址：</span>广东省 广州市 天河区</li>
        </ul>
    </div>

    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">

            {%for goods in goods_list%}
            <li>
                <a href="/{{goods.id}}"><img src="/static/{{goods.gpic}}"></a>
                <h4><a href="detail.html">{{goods.gtitle}}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{goods.gprice}}</span>
                    <span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>
            {%endfor%}
        </ul>
    </div>
</div>


{% endblock right_content %}

templates/user/user_center_order.html
{%extends 'user/base.html'%}
{% block right_content %}
<div class="right_content clearfix">
    <h3 class="common_title2">全部订单</h3>
    {% for order in order_list %}
    <ul class="order_list_th w978 clearfix">
        <li class="col01">{{order.order_date}}</li>
        <li class="col02">订单号：{{order.order_id}}</li>
        {% if order.order_Pay == 1 %}
        <li class="col02 stress">已支付</li>
        {% else %}
        <li class="col02 stress">未支付</li>
        {% endif %}
    </ul>
    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                {% for item in order.orderdetail_set.all %}
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="/static/{{item.order_goods.goods_picture}}"></li>
                    <li class="col02">
                        {{item.order_goods.goods_title}}
                        <em><span>{{item.order_price}}</span>元/{{item.order_goods.goods_unit}}</em>
                    </li>
                    <li class="col03">{{item.order_count}}个</li>
                    <li class="col04"></li>
                </ul>
                {% endfor %}
            </td>
            <td width="15%">{{order.order_total}}元</td>
            {% if order.order_Pay == 1 %}
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
            {% else %}
            <td width="15%">未付款</td>
            <td width="15%"><a href="/order/pay&{{order.order_id}}/" class="oper_btn">去付款</a></td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% endfor %}
    <div class="pagenation">
        {% if order_list.has_previous %}
        <a href="/user/user_center_order&{{order_list.previous_page_number}}/">
            上一页
        </a>
        {% endif %}
    <!--分页 ： plist 一共多少页  pageid 当前页  orderlist paginator按照两个一页，分的，页的指向对象-->
    {% if len_page_list < 4  %}
        {% if len_page_list == 1 %}
            <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
        {% elif len_page_list == 2 %}
            {% if page_id == 1 %}
            <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
            <a href="/user/user_center_order&{{page_next}}/" >{{page_next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{page_previous}}/" >{{page_previous}}</a>
            <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
            {% endif %}
        {% elif len_page_list == 3%}

            {% if page_id == 1 %}
            <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
            <a href="/user/user_center_order&{{page_next}}/" >{{page_next}}</a>
            {% elif page_id == 2 %}
            <a href="/user/user_center_order&{{page_previous}}/" >{{page_previous}}</a>
            <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
            <a href="/user/user_center_order&{{page_next}}/" >{{page_next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{page_previous}}/" >{{page_previous}}</a>
            <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
            {% endif %}
        {% endif %}
    {% elif page_id < len_page_list %}
        {% if order_list.has_previous  %}
        <a href="/user/user_center_order&{{page_previous}}/" >{{page_previous}}</a>
        <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
        <a href="/user/user_center_order&{{page_next}}/" >{{page_next}}</a>
        {% else %}
        <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
        <a href="/user/user_center_order&{{page_next}}/" >{{page_next}}</a>
        {% endif %}
    {% else %}
        <a href="/user/user_center_order&{{page_previous}}/" >{{page_previous}}</a>
        <a href="/user/user_center_order&{{page_id}}/" class="active">{{page_id}}</a>
    {% endif %}


        {% if order_list.has_next %}
        <a href="/user/user_center_order&{{order_list.next_page_number}}/">下一页></a>
        {% endif %}
    </div>
</div>


{%endblock right_content %}

templates/user/user_center_site.html
{%extends 'user/base.html'%}
{%block right_content %}
<div class="right_content clearfix">
    <h3 class="common_title2">收货地址</h3>
    <div class="site_con">
        <dl>
            <dt>当前地址：</dt>
            <dd>{{user_address}} ({{user_addressee}} 收) 电话：{{user_phone}} 邮编：{{user_post_code}}</dd>
        </dl>
    </div>
    <h3 class="common_title2">编辑地址</h3>
    <div class="site_con">
        <form action="/user/site/" method="post">
            {%csrf_token%}
            <div class="form_group">
                <label>收件人：</label>
                <input type="text" name="ushou" value="{{user_addressee}}">
            </div>
            <div class="form_group form_group2">
                <label>详细地址：</label>
                <textarea class="site_area" name="uaddress">{{user_address}}</textarea>
            </div>
            <div class="form_group">
                <label>邮编：</label>
                <input type="text" name="uyoubian" value="{{user_post_code}}">
            </div>
            <div class="form_group">
                <label>手机：</label>
                <input type="text" name="uphone" value="{{user_phone}}">
            </div>

            <input type="submit" name="" value="提交" class="info_submit">
        </form>
    </div>
</div>

{%endblock right_content %}